### ISSUE TITLE
Action fails in win22/20220814.1 environment

### ISSUE THREAD

**Issue by TheMostDiligent** [microsoft/msvc-code-analysis-action#20]
After GitHub updated its Windows environment to[ win22/20220814.1](https://github.com/actions/runner-images/blob/win22/20220814.1/images/win/Windows2022-Readme.md), the action started failing with the following error:

```
Loaded 'D:\a\DiligentCore\build\.cmake\api\v1\reply\index-2022-08-16T23-03-14-0395.json' reply generated from CMake API.
Error: Error: Unknown MSVC toolset layout
```

Absolutely same setup worked ok in [win22/20220808.1](https://github.com/actions/runner-images/blob/win22/20220808.1/images/win/Windows2022-Readme.md)

**Comment by Pirulax** [comment]
Same for us, build fails.
Relevant source code: https://discord.com/channels/874507673943539752/884291206157316166/1009643571202248714

**Comment by Pirulax** [comment]
Same for us, build fails.
Relevant source code: https://github.com/microsoft/msvc-code-analysis-action/blob/main/index.js#L259

**Comment by TheMostDiligent** [comment]
@Pirulax FYI, as a workaround I downgraded windows image to windows-2019 (and VS2019) and it works

**Comment by d-winsor** [comment]
Look like their was a casing change in the Visual Studio layout for the MSVC toolset.

**Comment by Pirulax** [comment]
Thank you!
